name: Pull

inputs:
  # SSH
  host:
    required: true
  username:
    required: true
  port:
    required: true
  ssh-private-key:
    required: true

  # Docker
  image-name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Pull new image on VPS
      continue-on-error: true
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        port: ${{ inputs.port }}
        key: ${{ inputs.ssh-private-key }}
        script: |
          docker pull ${{ inputs.image-name }}
