name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: 🐛 Debug Inputs
      #   shell: bash
      #   run: |
      #     echo "Host: ${{ inputs.host }}"
      #     echo "Username: ${{ inputs.username }}"
      #     echo "Port: ${{ inputs.port }}"
      #     echo "Application Port: ${{ inputs.application-port }}"
      #     echo "Container Port: ${{ inputs.container-port }}"
      #     echo "Image Name: ${{ inputs.image-name }}"
      #     echo "Container Name: ${{ inputs.container-name }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: "./.github/templates/build-and-push"
        with:
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          image-name: mcdominik/super-app
          context: ./example-app
          file: ./example-app/Dockerfile

      - name: Pull new image on server
        uses: "./.github/templates/pull"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ vars.USERNAME }}
          port: ${{ vars.PORT }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          image-name: mcdominik/super-app

  deploy-green:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy green
        uses: "./.github/templates/deploy"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ vars.USERNAME }}
          port: ${{ vars.PORT }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          application-port: 5000
          container-port: 4001
          image-name: mcdominik/super-app
          container-name: super-app-green

  deploy-blue:
    runs-on: ubuntu-latest
    needs: deploy-green
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy blue
        uses: "./.github/templates/deploy"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ vars.USERNAME }}
          port: ${{ vars.PORT }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          application-port: 5000
          container-port: 4000
          image-name: mcdominik/super-app
          container-name: super-app-blue

  clean:
    runs-on: ubuntu-latest
    needs: deploy-blue
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean old docker images
        uses: "./.github/templates/clean"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ vars.USERNAME }}
          port: ${{ vars.PORT }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
